### PR TITLE
Update commands.md

### PR DESCRIPTION
**Pull request by magnolia-k**
cherry-pick from https://github.com/ddpaimon/scalatra-website/tree/2.5

@ddpaimon

### CODE REVIEW

**Comment by takezoe** [comment]
@magnolia-k Thanks. I looked your fix for commands example (https://github.com/scalatra/scalatra-website-examples/pull/35). Maybe it should be fixed the following code in documentation as well.

```scala
  post("/todos") {
    val todo = new Todo(-1, params("name"))
    TodoData.add(TodoData.newTodo(params("name")))
    redirect("/")
  }
```

**Comment by magnolia-k** [comment]
As you pointed out.

It seems that there are places to fix many other examples of commands.md code, so we will fix it together.

**Comment by magnolia-k** [comment]
Corrected according to example code

**Comment by takezoe** [comment]
Thanks. Is it all? I would like to merge and redeploy the web site, so let me know if you will fix other codes in the commands document.

**Comment by takezoe** [comment]
Merged and deployed.

**Comment by magnolia-k** [comment]
There are many other places I want to fix, but it will take time, so I will make another PR.

**Pull request merged**
