### PR TITLE
Updated CORS documentation how to configure wildcard domains

### LINKED ISSUE #180: Update the CORS documentation to explicitly state behavior
We've run into problems with CORS after upgrading scalatra to any version newer than 2.5.0.

This bug was filed https://github.com/scalatra/scalatra/issues/797 and eventually resolved with help of @takezoe. 

I would like the CORS documentation page updated with: 

 1. Mixing in CorsSupport is not required, the documentation makes it looks like it is required.
 2. Include this explanation into CORS documentation page:

In Scalatra 2.5.1, a security issue in CORSSupport has been fixed in https://github.com/scalatra/scalatra/pull/635. As the result, the origin which is sent from a client must be declared in the init param org.scalatra.cors.allowedOrigins like:

    context.initParameters("org.scalatra.cors.allowedOrigins") = "http://example.com:8080,http://foo.example.com"

**The default of this init param is "*". In this case, you have to add following init param:**

    context.initParameters("org.scalatra.cors.allowCredentials") = "false"

### PR DESCRIPTION
**Pull request by toefel18**
fixes #180 by updating the documentation how to use CORS for wildcard domains.

### CODE REVIEW

**Comment by takezoe** [comment]
@toefel18 Great thanks! I looked your fix and I wonder we should change the default settings of CORS support in the future version.

**Comment by toefel18** [comment]
@takezoe I also was thinking that the setting allowCredentials should not be true by default. It's more logical to default that to false unless you explicitly want cookies. Also, the current default allowedOrigins=* and allowCredentials=true break CORS. Users who upgrade (like us) will suddenly have problems, without a clear indication why

**Comment by toefel18** [comment]
Shall I create an issue in scalatra/scalatra?

**Comment by takezoe** [comment]
@toefel18 Yes, please! I would like to change the default settings of CORS in Scalatra 2.7.0 which is the next major update.

**Comment by toefel18** [comment]
Done https://github.com/scalatra/scalatra/issues/800

**Pull request merged**
