### PR TITLE
Update commands.md

### PR DESCRIPTION
**Pull request by ddpaimon**
Fixed links on scalatra apidocs.

### CODE REVIEW

**Comment by takezoe** [comment]
@ddpaimon Thanks, but the web site is now deploying from `master` branch.

**Comment by magnolia-k** [comment]
@ddpaimon

I made a PR with cherry-pick so that it can be merged into the master branch

https://github.com/scalatra/scalatra-website/pull/137

**Comment by ddpaimon** [comment]
How to do better next time?

**Comment by takezoe** [comment]
@ddpaimon It's good enough to send pull request against the master branch simply.

**Comment by takezoe** [comment]
Merged with #137

**Pull request closed without merging**
