### PR TITLE
Updated according to the latest template

### PR DESCRIPTION
**Pull request by magnolia-k**

### CODE REVIEW

**Comment by takezoe** [comment]
@magnolia-k Why did you remove shortcodes (like `{{< 2-5-scalatra_version >}}`)?
We are only using shortcodes partly in the current documentation. So it might be nice to stop to use it to reference library versions.

**Comment by magnolia-k** [comment]
Oops, I should have corrected '2-5-jetty_version'. We modified all to use shortcodes.

**Comment by takezoe** [comment]
@magnolia-k Thanks for fix. But I think shortcodes is not so good solution to reference libraries version in fact. Let me know if you find a better solution in hugo ;-)

**Comment by magnolia-k** [comment]
I really think so.
I will search for something good.

**Comment by futurechimp** [comment]
I agree that the shortcodes are not great, but I couldn't find a better solution - maybe you'll have better luck than me :). Great work on the docs by the way, all the improvements are really nice.

**Pull request merged**
