### PR TITLE
2.3.1 release (2.4)

### PR DESCRIPTION
**Pull request by seratch**
Add 2.3.1 release in the `Versions` section and add other changes:

- remove 2.0.x because they're no longer maintained
- remove 2.2.x against Scala 2.9 because that's no longer actively maintained

If the above extra changes are not reasonable, I'll revert them. Please let me know.

### CODE REVIEW

**Comment by rossabaker** [comment]
:+1:  Merge this after we release 2.3.1?

**Comment by seratch** [comment]
Thanks :+1: I'm working on 2.3.1 release now. I'll ping you after finishing that.

**Comment by seratch** [comment]
2.3.1 release has been done.

**Comment by seratch** [comment]
I'm going to release 2.4.0.M3 too. It may be about time to consider RCs for 2.4.0 final.

**Comment by seratch** [comment]
2.4.0.M3 release has been done. Would you please merge this PR and https://github.com/scalatra/scalatra-website/pull/88?

I'll work on announcements for 2.3.0 and 2.4.0.M3 release. I already have a permission to publish them to notes.implicit.ly. After review, I'd like to publish an announcement there.

**Comment by rossabaker** [comment]
Fantastic, thank you!

I agree, I think it's about time to ship 2.4 final.  I can't think of any major efforts still underway.

**Comment by seratch** [comment]
@rossabaker The website has not been updated yet. Should I do anything extra? If so, please let me know.

**Comment by rossabaker** [comment]
The bundler job failed: https://jenkins.backchat.io/job/scalatra-website-2.3/35/console.  I guess there's some floating dependency that now requires Ruby 2.2.0?  I'm trying to install it with rbenv now.

**Comment by seratch** [comment]
>I guess there's some floating dependency that now requires Ruby 2.2.0?

No there isn't. However, I'd like to upgrade Ruby lang version because 1.9.3 is too old ([eol announcement](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/)). Sorry for bothering you but please upgrade the Ruby version. Thanks in advance.

**Comment by rossabaker** [comment]
I installed Ruby 2.2.0, and it then complained that bundle wasn't installed for that:
https://jenkins.backchat.io/job/scalatra-website-2.3/38/console

This used to work fine, so clearly something was using a dynamic version of Ruby.  I set RBENV_VERSION=1.9.3-p392 in the job, and both builds worked.  This isn't a good solution because of the EOL, but I don't know rbenv very well.  Is there a quick thing I can do to fix the problem shown in build 38 without just using an old Ruby?

**Comment by seratch** [comment]
I see. It's ok to use old Ruby for now.

```
+ bundle install
rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  1.9.3-p194
  1.9.3-p392
```

The reason for this error seems to be lack of previously executing `gem install bundler` && `rbenv rehash`. Basically the Ruby version doesn't matter for building scalatra.org. I'd like to fix this issue. Would you please grant me to configure the Jenkins jobs on backchat.io?

**Comment by rossabaker** [comment]
I'm not sure how to do the Jenkins admin. @casualjim?

**Pull request merged**
