### PR TITLE
Describe how to use a custom location for ScalatraBootstrap in web.xml

### PR DESCRIPTION
**Pull request by cstroe**
This is one of the documentation pieces that eluded me.  It makes sense for it to be in the Configuration section since that's where all the `web.xml` docs seem to be.

### CODE REVIEW

**Comment by cstroe** [comment]
This seems to be related to #50

**Comment by takezoe** [comment]
@cstroe Thanks for your request, but the current published branch is `feature/hugo`. Could you start your work from this branch?
https://github.com/scalatra/scalatra-website/tree/feature/hugo

Originally this branch should be a default branch of this repository, but I can't configure because I don't have administration right for this repository. I will ask administrators to do so.

**Comment by dozed** [comment]
@takezoe Should we merge `feature/hugo` to `master`?

I can update the Travis build to build from `master`.

**Comment by cstroe** [comment]
Re-opened PR here: https://github.com/scalatra/scalatra-website/pull/131

**Comment by takezoe** [comment]
@dozed Yes. I think it is about time to merge.

**Pull request closed without merging**
