### PR TITLE
Feature/hugo

### PR DESCRIPTION
**Pull request by futurechimp**
I've converted the whole site to use Hugo instead of Jekyll. In theory, this pull request should get us to a deployable `gh-pages` deploy once it's generated. 

Somebody else should take a look at it to confirm things build properly for them - then the generated files will need to be committed as well. @dozed @rossabaker I think I don't have proper org permissions to deploy the `gh-pages` branch but I haven't looked into it too hard and could just be mistaken.

### CODE REVIEW

**Comment by takezoe** [comment]
I'm testing this branch and got some issues:

- Some pages look un-existing layout such as `guide` or `oldguide`. These pages are not generated by hugo. Should they use a default layout?
- Next and Prev link in the footer is confused. Maybe it should be removed.
- Versions defined in `layouts/shortcodes` isn't correct. We have to update them according the latest versions.

I would like fix them and sync with 2.5 branch to replace the Scalatra website with the hugo version.

**Comment by takezoe** [comment]
@dozed I would like to merge this branch. Since the website is deployed to scalatra-docbuild repository, should we merge this branch into `master` instead of `gh-pages`?

**Comment by dozed** [comment]
@takezoe yes, definitely.
For the website build this line needs to get updated: https://github.com/scalatra/scalatra-docbuild/blob/master/hello.sh#L55-L57

**Comment by takezoe** [comment]
@dozed Since `master` didn't exist in this repository, I pushed this branch as `master`. However I don't have permission to manage this repository, so I can't change the default branch to `master`. Could you do it?

**Comment by takezoe** [comment]
Since `feature/hugo` branch has been pushed as `master`, close this request.

**Pull request closed without merging**
